### ISSUE TITLE
Yo-Kai Watch (USA)

### ISSUE THREAD

**Issue by LaReunion974** [Panda3DS-emu/Panda3DS-Games-List#36] opened 2023-09-07 13:13 UTC
### Game Name (and version if necessary)

Yo-Kai Watch 

### Hardware Specs (If necessary)

CPU: Processor
12th Gen Intel(R) Core(TM) i3-12100F
	base speed : 3,30 GHz
	Cores : 4
	Threads :	8
GPU: GPU 0
	NVIDIA GeForce RTX 3050
	Dedicated Memory (Vram): 8,0 Go
RAM: Memory
	16,0 Go DDR4
	Speed :	3200 MHz
	
### Operating System

Windows 11 Pro Insider Preview 23546-1546

### Game State

Game crash during cinematic

Log: 
at the game launch:
[Warning] [GSP::GPU VaddrToPaddr] Unknown virtual address 1F600000
at the crash:
[FATAL] WaitSynchronizationN: Bad object handle FFFF8008

### Screenshots

![image](https://github.com/Panda3DS-emu/Panda3DS-Games-List/assets/102532446/fbe21dfc-c7f4-4c3e-804c-14966e15ea27)

![image](https://github.com/Panda3DS-emu/Panda3DS-Games-List/assets/102532446/f60056f0-d376-4e43-8f7b-3ada5fa43bf9)

**Comment by wheremyfoodat** [comment] 2023-09-07 13:16
Dupe of #29

**Closed as completed by wheremyfoodat** 2023-09-07 13:16 UTC
