### ISSUE TITLE
Detective Pikachu

### ISSUE THREAD

**Issue by SuperTavor** [Panda3DS-emu/Panda3DS-Games-List#88] opened 2023-10-13 11:54 UTC
### Game Name (and version if necessary)

Detective Pikachu

### Hardware Specs (If necessary)

CPU: 13th Gen Intel(R) Core(TM) i7-13700F   2.10 GHz
GPU: NVIDIA RTX 3060

### Operating System

Windows 11

### Game State

Won't start.
Error:
[FATAL] Failed to find paddr

**Comment by KostaSaizo7** [comment] 2023-10-13 14:45
Duplicate of #24

**Closed as completed by KostaSaizo7** 2023-10-13 14:45 UTC
