### ISSUE TITLE
Bravely Second : End Layer - top screen is completely black

### ISSUE THREAD

**Issue by extherian** [Panda3DS-emu/Panda3DS-Games-List#155] opened 2024-10-25 08:43 UTC
### Game Name (and version if necessary)

Bravely Second

### Hardware Specs (If necessary)

5800X3D, 64GB DDR4 3600MT/s, RTX 4070

### Operating System

Windows 11

### Game State

The same problem as with Bravely Default, the game is unplayable without 3D rendering on the top screen. Apparently most likely to be a render-to-texture issue. 

### Screenshots

![374089591-7f8ff128-b322-47eb-b041-b75b79c70dda](https://github.com/user-attachments/assets/3ad91e36-326c-4639-815d-1f18dd1e146f)

### Additional information

Unlike Citra, the character icon on the save file is displayed correctly and does not overlap the file window.

**Comment by wheremyfoodat** [comment] 2024-10-25 08:46
Marking as duplicate of #57

**Closed as completed by wheremyfoodat** 2024-10-25 08:46 UTC
