### ISSUE TITLE
Devil Survivor Over Clock (Japan)

### ISSUE THREAD

**Issue by ghost** [Panda3DS-emu/Panda3DS-Games-List#110] opened 2024-03-07 21:29 UTC
### Game Name (and version if necessary)

Devil Survivor Over Clock

### Operating System

Windows 11 23H2

### Game State

Playable without Audio

**Comment by ghost** [comment] 2024-03-08 17:18
i mean

**Comment by KostaSaizo7** [comment] 2024-03-18 11:40
Duplicate of https://github.com/Panda3DS-emu/Panda3DS-Games-List/issues/107

**Closed as completed by KostaSaizo7** 2024-03-18 11:40 UTC
