### ISSUE TITLE
Colors! 3D

### ISSUE THREAD

**Issue by FelipePlayzYT** [Panda3DS-emu/Panda3DS-Games-List#143] opened 2024-03-14 20:53 UTC
### Game Name (and version if necessary)

Colors! 3D

### Hardware Specs (If necessary)

CPU: Intel I3-7020U
GPU: Intel HD Graphics 620

### Operating System

Windows 11

### Game State

The game works, but cannot be progressed any further on the image provided due to it needing to toggle the 3d slider thing, and that's not implemented on the emulator.

### Screenshots

![image](https://github.com/Panda3DS-emu/Panda3DS-Games-List/assets/54115676/f67014ad-5bf0-45fb-91db-a37ae0e6ad85)

**Comment by drewbyhk** [comment] 2024-03-14 23:37
Dupe of #138.

**Comment by wheremyfoodat** [comment] 2024-03-14 23:40
Moved the info from here to #138

**Closed as completed by wheremyfoodat** 2024-03-14 23:40 UTC
