### ISSUE TITLE
 Bravely Default - top screen is completely black

### ISSUE THREAD

**Issue by extherian** [Panda3DS-emu/Panda3DS-Games-List#154] opened 2024-10-25 08:40 UTC
### Game Name (and version if necessary)

Bravely Default

### Hardware Specs (If necessary)

5800X3D, 64GB DDR4 3600MT/s, RTX 4070

### Operating System

Windows 11

### Game State

This game is unplayable as the top screen is where you control the character and move around the game world. Only the 2D "Speak" icon is displayed, so 2D elements work fine, it's just 3D rendering that is broken. Apparently most likely to be a render-to-texture issue. 

### Screenshots

![374088221-520de865-b849-4152-badd-033a634c4cc4](https://github.com/user-attachments/assets/cf065596-f2c9-46e1-aafa-e2815eaf2aa9)

### Additional information

Unlike Citra, the character icon on the save file is displayed correctly and does not overlap the file window.

**Comment by wheremyfoodat** [comment] 2024-10-25 08:42
(Duplicate of #56, please check games don't already have an entry)

**Closed as completed by wheremyfoodat** 2024-10-25 08:42 UTC
